// packages/vue3/test-app/Pages/FormHelper/Transform.vue
<script setup>
import { useForm } from '@inertiajs/vue3'

const methodNameTransforms = {
  post: 'bar',
  put: 'baz',
  patch: 'foo',
  delete: 'bar'
}

const form = useForm({
  name: 'foo',
  remember: false,
}, {
  transform: (data, method) => {
    return { ...data, name: methodNameTransforms[method] }
  }
})

const postForm = () => {
  form
    .post('/dump/post')
}

const putForm = () => {
  form
    .put('/dump/put')
}

const patchForm = () => {
  form
    .patch('/dump/patch')
}

const deleteForm = () => {
  form
    .delete('/dump/delete')
}
</script>

<template>
  <div>
    <label>
      Full Name
      <input type="text" id="name" name="name" v-model="form.name" />
    </label>
    <label>
      Remember Me
      <input type="checkbox" id="remember" name="remember" v-model="form.remember" />
    </label>

    <button @click="postForm" class="post">POST form</button>
    <button @click="putForm" class="put">PUT form</button>
    <button @click="patchForm" class="patch">PATCH form</button>
    <button @click="deleteForm" class="delete">DELETE form</button>
  </div>
</template>

// packages/svelte/test-app/Pages/FormHelper/Transform.svelte
<script>
  import { useForm } from '@inertiajs/svelte'

  const methodNameTransforms = {
    post: 'bar',
    put: 'baz',
    patch: 'foo',
    delete: 'bar'
  }

  const form = useForm({
    name: 'foo',
    remember: false,
  }, { 
    transform: (data, method) => ({ ...data, name: methodNameTransforms[method]})
  })

  const postForm = () => {
    $form.post('/dump/post')
  }

  const putForm = () => {
    $form.put('/dump/put')
  }

  const patchForm = () => {
    $form.patch('/dump/patch')
  }

  const deleteForm = () => {
    $form.delete('/dump/delete')
  }
</script>

<div>
  <label>
    Full Name
    <input type="text" id="name" name="name" bind:value={$form.name} />
  </label>
  <label>
    Remember Me
    <input type="checkbox" id="remember" name="remember" bind:checked={$form.remember} />
  </label>

  <button on:click={postForm} class="post">POST form</button>
  <button on:click={putForm} class="put">PUT form</button>
  <button on:click={patchForm} class="patch">PATCH form</button>
  <button on:click={deleteForm} class="delete">DELETE form</button>
</div>
